import { BrushSettings } from '../types';

export const DEFAULT_BRUSH_PRESETS: BrushSettings[] = [
  // --- Art Draw Studio [Watercolor] Sub Tools ---
  {
    id: 'opaque-watercolor',
    name: 'Opaque watercolor',
    category: 'watercolor',
    size: 24,
    opacity: 0.88,
    flow: 0.85,
    hardness: 0.7,
    spacing: 0.08,
    stabilization: 8,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.35,
    colorSmear: 0.6,
    smartCorrection: true,
    dualBrush: {
      enabled: true,
      tipShape: 'stipple',
      blendMode: 'multiply',
      sizeRatio: 0.85,
      spacing: 0.12,
      hardness: 0.6,
      textureIntensity: 0.65,
      angle: 0,
      jitter: 0.06,
    },
    jitter: 0,
  },
  {
    id: 'transparent-watercolor',
    name: 'Transparent watercolor',
    category: 'watercolor',
    size: 28,
    opacity: 0.45,
    flow: 0.5,
    hardness: 0.35,
    spacing: 0.1,
    stabilization: 6,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.65,
    jitter: 0,
  },
  {
    id: 'dense-watercolor',
    name: 'Dense watercolor',
    category: 'watercolor',
    size: 20,
    opacity: 0.95,
    flow: 0.9,
    hardness: 0.85,
    spacing: 0.06,
    stabilization: 10,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.25,
    jitter: 0,
  },
  {
    id: 'smooth-watercolor',
    name: 'Smooth watercolor',
    category: 'watercolor',
    size: 26,
    opacity: 0.6,
    flow: 0.6,
    hardness: 0.45,
    spacing: 0.09,
    stabilization: 8,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.5,
    jitter: 0,
  },
  {
    id: 'paint-and-apply',
    name: 'Paint and apply',
    category: 'watercolor',
    size: 32,
    opacity: 0.92,
    flow: 0.85,
    hardness: 0.75,
    spacing: 0.08,
    stabilization: 7,
    tipShape: 'flat',
    angle: 20,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.4,
    jitter: 0.02,
  },
  {
    id: 'watercolor-brush',
    name: 'Watercolor brush',
    category: 'watercolor',
    size: 22,
    opacity: 0.78,
    flow: 0.75,
    hardness: 0.6,
    spacing: 0.07,
    stabilization: 9,
    tipShape: 'calligraphy',
    angle: 35,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.45,
    jitter: 0,
  },
  {
    id: 'running-color-edge',
    name: 'Running color edge watercolor',
    category: 'watercolor',
    size: 25,
    opacity: 0.7,
    flow: 0.8,
    hardness: 0.75,
    spacing: 0.08,
    stabilization: 8,
    tipShape: 'stipple',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.55,
    jitter: 0.04,
  },
  {
    id: 'watery',
    name: 'Watery',
    category: 'watercolor',
    size: 38,
    opacity: 0.32,
    flow: 0.4,
    hardness: 0.25,
    spacing: 0.12,
    stabilization: 6,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.8,
    jitter: 0,
  },
  {
    id: 'emphasizing-texture',
    name: 'Emphasizing texture',
    category: 'watercolor',
    size: 24,
    opacity: 0.82,
    flow: 0.75,
    hardness: 0.7,
    spacing: 0.14,
    stabilization: 5,
    tipShape: 'stipple',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0.15,
  },
  {
    id: 'uneven-layering',
    name: 'Uneven layering brush',
    category: 'watercolor',
    size: 30,
    opacity: 0.68,
    flow: 0.65,
    hardness: 0.5,
    spacing: 0.1,
    stabilization: 7,
    tipShape: 'flat',
    angle: 40,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.6,
    jitter: 0.03,
  },
  {
    id: 'soothing-watercolor',
    name: 'Soothing watercolor',
    category: 'watercolor',
    size: 28,
    opacity: 0.42,
    flow: 0.45,
    hardness: 0.3,
    spacing: 0.11,
    stabilization: 7,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.7,
    jitter: 0,
  },
  {
    id: 'wet-bleed-blender',
    name: 'Wet bleed blender',
    category: 'watercolor',
    size: 42,
    opacity: 0.25,
    flow: 0.3,
    hardness: 0.15,
    spacing: 0.14,
    stabilization: 5,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.9,
    jitter: 0.02,
  },

  // --- Art Draw Studio [India Ink & Pens] ---
  {
    id: 'g-pen',
    name: 'G-Pen',
    category: 'ink',
    size: 8,
    opacity: 1.0,
    flow: 1.0,
    hardness: 0.98,
    spacing: 0.05,
    stabilization: 15,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: false,
    mixGroundColor: false,
    colorMixRatio: 0,
    smartCorrection: true,
    taperFactor: 0.75,
    jitter: 0,
  },
  {
    id: 'real-g-pen',
    name: 'Real G-Pen',
    category: 'ink',
    size: 10,
    opacity: 0.96,
    flow: 0.95,
    hardness: 0.88,
    spacing: 0.07,
    stabilization: 18,
    tipShape: 'stipple',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: false,
    colorMixRatio: 0.1,
    smartCorrection: true,
    taperFactor: 0.65,
    jitter: 0.04,
  },
  {
    id: 'calligraphy-pen',
    name: 'Calligraphy Pen',
    category: 'ink',
    size: 16,
    opacity: 1.0,
    flow: 1.0,
    hardness: 0.92,
    spacing: 0.06,
    stabilization: 8,
    tipShape: 'calligraphy',
    angle: 45,
    pressureSize: true,
    pressureOpacity: false,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0,
  },
  {
    id: 'mapping-pen',
    name: 'Mapping (Maru) Pen',
    category: 'ink',
    size: 4,
    opacity: 1.0,
    flow: 1.0,
    hardness: 1.0,
    spacing: 0.04,
    stabilization: 16,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: false,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0,
  },

  // --- Art Draw Studio [Pencil] Sub Tools ---
  {
    id: 'pencil-rough',
    name: 'Rough Pencil',
    category: 'pencil',
    size: 6,
    opacity: 0.75,
    flow: 0.7,
    hardness: 0.6,
    spacing: 0.15,
    stabilization: 4,
    tipShape: 'stipple',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0.12,
  },
  {
    id: 'pencil-soft',
    name: 'Design Pencil',
    category: 'pencil',
    size: 14,
    opacity: 0.6,
    flow: 0.6,
    hardness: 0.4,
    spacing: 0.1,
    stabilization: 6,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0.05,
  },
  {
    id: 'pencil-real',
    name: 'Real Pencil',
    category: 'pencil',
    size: 9,
    opacity: 0.8,
    flow: 0.75,
    hardness: 0.55,
    spacing: 0.12,
    stabilization: 6,
    tipShape: 'stipple',
    angle: 25,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0.08,
  },

  // --- Art Draw Studio [Thick Paint & Realistic] ---
  {
    id: 'oil-paint',
    name: 'Thick Oil Paint',
    category: 'paint',
    size: 28,
    opacity: 0.88,
    flow: 0.85,
    hardness: 0.75,
    spacing: 0.08,
    stabilization: 8,
    tipShape: 'flat',
    angle: 30,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.55,
    colorSmear: 0.8,
    dualBrush: {
      enabled: true,
      tipShape: 'flat',
      blendMode: 'multiply',
      sizeRatio: 0.9,
      spacing: 0.1,
      hardness: 0.8,
      textureIntensity: 0.75,
      angle: 30,
      jitter: 0.02,
    },
    jitter: 0.03,
  },
  {
    id: 'dry-gouache',
    name: 'Dry Gouache',
    category: 'paint',
    size: 34,
    opacity: 0.9,
    flow: 0.85,
    hardness: 0.8,
    spacing: 0.09,
    stabilization: 6,
    tipShape: 'flat',
    angle: 15,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: true,
    colorMixRatio: 0.35,
    jitter: 0.04,
  },

  // --- Art Draw Studio [Airbrush] ---
  {
    id: 'airbrush-soft',
    name: 'Soft Airbrush',
    category: 'airbrush',
    size: 45,
    opacity: 0.35,
    flow: 0.3,
    hardness: 0.1,
    spacing: 0.08,
    stabilization: 3,
    tipShape: 'round',
    angle: 0,
    pressureSize: true,
    pressureOpacity: true,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0,
  },
  {
    id: 'spray-droplet',
    name: 'Droplet Spray',
    category: 'airbrush',
    size: 50,
    opacity: 0.8,
    flow: 0.5,
    hardness: 0.9,
    spacing: 0.25,
    stabilization: 2,
    tipShape: 'stipple',
    angle: 0,
    pressureSize: true,
    pressureOpacity: false,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0.4,
  },
  {
    id: 'chisel-marker',
    name: 'Flat Chisel Marker',
    category: 'marker',
    size: 22,
    opacity: 0.9,
    flow: 0.9,
    hardness: 0.9,
    spacing: 0.08,
    stabilization: 7,
    tipShape: 'chisel',
    angle: 60,
    pressureSize: false,
    pressureOpacity: true,
    mixGroundColor: false,
    colorMixRatio: 0,
    jitter: 0,
  }
];

export const BLEND_MODE_OPTIONS = [
  { label: 'Normal', value: 'source-over' },
  { label: 'Multiply', value: 'multiply' },
  { label: 'Screen', value: 'screen' },
  { label: 'Overlay', value: 'overlay' },
  { label: 'Darken', value: 'darken' },
  { label: 'Lighten', value: 'lighten' },
  { label: 'Color Dodge', value: 'color-dodge' },
  { label: 'Color Burn', value: 'color-burn' },
  { label: 'Hard Light', value: 'hard-light' },
  { label: 'Soft Light', value: 'soft-light' },
  { label: 'Difference', value: 'difference' },
] as const;
